services:
  altinn_apps_monitoring_postgres:
    image: 'postgres:16@sha256:0b08171b5cdbf3214c42dbde17883ccfbf494b5e018d837ffe3fee91a3aec5c2'
    container_name: monitoring_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=platform_monitoring_admin
      - POSTGRES_PASSWORD=Password
    ports:
      - '5432:5432'
    volumes:
      - ./infra/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  altinn_apps_monitoring_pgadmin:
    image: 'dpage/pgadmin4:9.16@sha256:40fa840c5bb7c8463957f1255b01283732c2d8c9396a956d180f8e6c296753b3'
    container_name: monitoring_pgadmin
    restart: unless-stopped
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: platform_monitoring_admin@altinn.no
      PGADMIN_DEFAULT_PASSWORD: Password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./infra/servers.json:/pgadmin4/servers.json

  altinn_apps_monitoring_lgtm:
    image: 'docker.io/grafana/otel-lgtm:0.11@sha256:15b963783b3dc24a6256ebc1bffd4fc6c133348810faf86ecaa939912fd311b6'
    container_name: monitoring_lgtm
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
