apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: altinn-tools
  namespace: apps-monitor
spec:
  interval: 5m
  url: https://github.com/martinothamar/altinn-tools
  ref:
    branch: feat/apps-monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: altinn-apps-monitor-config
  namespace: apps-monitor
spec:
  interval: 10m
  targetNamespace: apps-monitor
  sourceRef:
    kind: GitRepository
    name: altinn-tools
  path: "./AppsMonitoring/infra/deployment/at24"
  prune: true
  timeout: 1m
secretGenerator:
- name: apps-monitor-appsettings
  disableNameSuffixHash: true
  files:
  - appsettings.at24.json
