apiVersion: v1
kind: Service
metadata:
  name: apps-monitor
spec:
  type: ClusterIP
  selector:
    app: apps-monitor
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
