name: Apps.Monitoring PR build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AppsMonitoring

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet '9.x'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-restore --no-build --logger "console;verbosity=detailed"
