name: Apps.Monitoring deploy

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.
    defaults:
      run:
        working-directory: ./AppsMonitoring

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: flux install
        uses: fluxcd/flux2/action@dd233c4fadef306a62b7893204f8e3817fecc2b2 # v2.9.5
        with:
          version: '2.5.1'

      - name: set vars
        id: vars
        run: |
          echo "registry=altinncr.azurecr.io" >> $GITHUB_OUTPUT
          echo "image=altinncr.azurecr.io/apps-monitor/image:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "image_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: az login
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALTINNCR_SUBSCRIPTION_ID }}

      - name: az acr login
        run: az acr login --name altinncr

      - name: docker build
        run: docker build -t ${{ steps.vars.outputs.image }} -f src/Altinn.Apps.Monitoring/Dockerfile .

      - name: scan image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: '${{ steps.vars.outputs.image }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: push image
        run: docker push ${{ steps.vars.outputs.image }}

      - name: yq install
        uses: mikefarah/yq@c14f446382944492701b16c1ddb48bb9dbe683e3 # v4.53.6

      - name: patch base with image tag
        run: |
          export APP_IMAGE="${{ steps.vars.outputs.image }}"
          export APP_IMAGE_TAG="${{ steps.vars.outputs.image_tag }}"
          yq -i '.metadata.annotations["altinn.no/image"] = env(APP_IMAGE)' infra/deployment/base/deployment.yaml
          yq -i '.metadata.annotations["altinn.no/image-tag"] = env(APP_IMAGE_TAG)' infra/deployment/base/deployment.yaml

      - name: push deployment
        run: |
          cd infra/deployment
          flux push artifact oci://${{ steps.vars.outputs.registry }}/apps-monitor/configs:${{ steps.vars.outputs.image_tag }} \
              --provider=generic \
              --reproducible \
              --path="." \
              --source="$(git config --get remote.origin.url)" \
              --revision="$(git branch --show-current)/${{ steps.vars.outputs.image_tag }}"
          flux tag artifact oci://${{ steps.vars.outputs.registry }}/apps-monitor/configs:${{ steps.vars.outputs.image_tag }} \
              --provider=generic \
              --tag at24