name: Apps.Monitoring promote

on:
  workflow_dispatch:
    inputs:
      from:
        description: "Environment to promote from"
        type: choice
        default: "at24"
        required: true
        options:
          - at24
          - tt02
      to:
        description: "Environment to promote to"
        type: choice
        default: "tt02"
        required: true
        options:
          - tt02
          - prod

jobs:
  promote:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AppsMonitoring

    steps:
      - name: validate inputs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            const allowedPromotions = [
              ['at24', 'tt02'],
              ['tt02', 'prod']
            ];
            const current = [
              '${{ github.event.inputs.from }}', 
              '${{ github.event.inputs.to }}'
            ];
            const promotion = allowedPromotions.find(c => c[0] === current[0] && c[1] === current[1]);
            if (!promotion) {
              core.setFailed(`Cannot promote from: ${current[0]} to ${current[1]}`);
            }

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: flux install
        uses: fluxcd/flux2/action@3b42b200d376430f0e24d35f1a600447d92da531 # No tag
        with:
          version: '2.5.1'

      - name: set vars
        id: vars
        run: |
          echo "registry=altinntjenesterregistry.azurecr.io" >> $GITHUB_OUTPUT

      # TODO: az login

      - name: Build latest artifact
        run: |
          flux tag artifact oci://${{ steps.vars.outputs.registry }}/configs/apps-monitor:${{ github.event.inputs.from }} \
              --provider=generic \
              --tag ${{ github.event.inputs.to }}
